name: Monikal-Чтосмотреть8
on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 14,15 * * *'
  watch:
    types: started
  repository_dispatch:
    types: bean_change
jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【Monikal-Чтосмотреть8】'
        run: |
          
          node Monikal-Чтосмотреть8.js
          
          
        env:
          jcboxbody: ${{ secrets.jcboxbody }}
